version: '3'
services:
  spidergraph:
    image: "skorfmann/spidergraph:$CIRCLE_BRANCH"
    environment:
      - HTTP_PROXY=http://mitmproxy:8080
      - HTTPS_PROXY=https://mitmproxy:8080
    depends_on:
      - mitmproxy
  mitmproxy:
    image: "skorfmann/mitmproxy"
    command: "bash -c \"mitmdump -S /flows/*.flow --server-replay-nopop --server-replay-kill-extra --anticache --set upstream_cert=false\""
    volumes:
      - ${PWD}/flows:/flows
      - ${PWD}/root-ca:/root/.mitmproxy
  integration-tests:
    image: "skorfmann/spidergraph:$CIRCLE_BRANCH"
    command: "npm run jest:integration"
    environment:
      - API_URL=http://spidergraph:8080
