# see https://circleci.com/docs/2.0/building-docker-images/#example
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: docker build -t skorfmann/spidergraph:$CIRCLE_BRANCH .
      - run: docker-compose -f docker-compose.test.yml up -d
      - run: docker run -it skorfmann/spidergraph:$CIRCLE_BRANCH npm run jest:integration
      # deploy the image
      # - run: docker push company/app:$CIRCLE_BRANCH
