version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      # - run: |
      #    docker login -u $DOCKER_USER -p $DOCKER_PASS
      #    docker run -d --name db company/proprietary-db:1.2.3

      # build the application image
      - run: docker-compose build

      # deploy the image
      # - run: docker push company/app:$CIRCLE_BRANCH
