query immobilienScout24
  @testPage(url: "https://www.immobilienscout24.de/expose/73098898")
  @match(url: "immobilienscout24.de/expose/\\d+") {

  realEstate {
    title @css(path: "#expose-title")
    price @css(path: ".is24qa-kaltmiete")
  }
}
